#!/bin/sh
mkdir -p .config/
ln -s ~/.dotfiles/.bashrc ~/
ln -s ~/.dotfiles/.Xdefaults ~/
ln -s ~/.dotfiles/bspwm ~/.config/
ln -s ~/.dotfiles/sxhkd ~/.config/
ln -s ~/.dotfiles/polybar ~/.config/
ln -s ~/.dotfiles/btops ~/.config/
ln -s ~/.dotfiles/dunst ~/.config/
ln -s ~/.dotfiles/fish ~/.config/
ln -s ~/.dotfiles/rofi ~/.config/
ln -s ~/.dotfiles/zathura ~/.config/
ln -s ~/.dotfiles/mpv ~/.config/
ln -s ~/.dotfiles/kitty ~/.config/
ln -s ~/.dotfiles/qutebrowser ~/.config/
ln -s ~/.dotfiles/picom ~/.config/
ln -s ~/.dotfiles/.xsetrate.sh ~/
ln -s ~/.dotfiles/boomer ~/.config/
ln -s ~/.dotfiles/helix ~/.config/
ln -s ~/.dotfiles/waybar ~/.config/
ln -s ~/.dotfiles/hypr ~/.config/
ln -s ~/.dotfiles/nvim ~/.config/
