theme = 'base16_transparent'

[keys.normal]
";" = "flip_selections"
"A-;" = "collapse_selection"

[keys.select]
"g" = { "e" = "goto_file_end" }
";" = "flip_selections"
"A-;" = "collapse_selection"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true
