#! /bin/sh

bspc monitor DisplayPort-2 -d I II III IV V VI
bspc monitor DVI-D-0       -d VII VIII IX

bspc config normal_border_color '#121212'
bspc config active_border_color '#323232'
bspc config focused_border_color '#323232'

bspc config border_width         2
bspc config window_gap           0
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

bspc config top_padding    20
bspc config bottom_padding 0
bspc config right_padding  0
bspc config left_padding   0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc rule -a screengrab state=floating
bspc rule -a java state=floating

killall polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

polybar default &
polybar default_laptop &
polybar defaultext &

xset      -dpms s off
setxkbmap -layout pl
xsetroot  -solid '#121212'
setxkbmap -option caps:super
xsetroot  -cursor_name left_ptr

pgrep -fl 'pidswallow -gl' || pidswallow -gl &
/usr/lib/kdeconnectd &
greenclip daemon &
sudo vnstatd -d
mocp -S &
bspm -d &
sxhkd &
btops &
dunst &

# numlockx on
