#!/bin/sh
bspc monitor DisplayPort-0 -d I II III IV V
bspc monitor DVI-D-0       -d VI VII V111

bspc monitor eDP1 -d I II III IV V

bspc config normal_border_color  '#121212'
bspc config active_border_color  '#121212'
bspc config focused_border_color '#323232'

bspc config border_width         2
bspc config window_gap           0
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

bspc config top_padding    20
bspc config bottom_padding 0
bspc config right_padding  0
bspc config left_padding   0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc rule -a Zathura	state=tiled

xrdb ~/.Xdefaults

killall polybar
polybar default &
polybar default_laptop &
polybar defaultext &

xset r rate 300 100
tset      -dpms s off
setxkbmap -layout pl
hsetroot  -solid '#121212'
setxkbmap -option caps:super
xsetroot  -cursor_name left_ptr
pgrep -f "xcape -e Super_L Escape" || xcape -e 'Super_L=Escape' # when super pressed once - act like escape
pgrep 'sxhkd' || sxhkd &
pgrep 'unclutter' || unclutter &
pgrep -f "$HOME/.scripts/spotify_hotkeys" || $HOME/.scripts/spotify_hotkeys &
killall btops;        btops &
sudo vnstatd -d
dunst &
picom &
clipster -d &